name: Unit Tests and Coverage

on:
  pull_request:
    branches:
      - main  # Or any other relevant branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Choose your Python version (3.8, 3.9, etc.)

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: pytest -v --cov=./chess_insights --cov-report=html

    - name: Archive Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/  # Standard output folder for pytest-cov
